In [ ]:
import pandas as pd 
import numpy as np  
import pickle

In [2]:
data = pd.read_csv("diabetes.csv")

In [3]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
X = data.drop("Outcome", axis = 1)
y = data["Outcome"]

In [6]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [7]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.23 , random_state = 42)

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
tree = DecisionTreeClassifier()

parameters_tree = {
    "max_depth" : [2 , 3 , 4 , 5],
    "criterion" : ["gini", "entropy"]
}

In [10]:
grid_tree = GridSearchCV(tree, parameters_tree, cv=5)
grid_tree.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5]})

In [11]:
print(grid_tree.best_params_)
print(grid_tree.best_score_ * 100)

{'criterion': 'gini', 'max_depth': 4}
76.13872667711152

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

parameters_knn = {
    "n_neighbors" : [2 , 3 , 4 , 5 ],
    "metric" : ["euclidean" , "manhattan"]

}

grid_knn = GridSearchCV(knn , parameters_knn , cv = 5)
grid_knn.fit(X_train , y_train)

print(grid_knn.best_params_)
print(grid_knn.best_score_ * 100)

{'metric': 'manhattan', 'n_neighbors': 5}
73.77581541091011

In [13]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
parameters_rf = {
    "n_estimators" : [100 , 200 , 300 , 400] , 
    "criterion" : ["gini" , "entropy"]
}

grid_rf = GridSearchCV(rf , parameters_rf , cv = 5)
grid_rf.fit(X_train , y_train)

print(grid_rf.best_params_)
print(grid_rf.best_score_ * 100)

{'criterion': 'entropy', 'n_estimators': 200}
77.66557470445805

In [14]:
best_rf = grid_rf.best_estimator_
y_pred = best_rf.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Test Accuracy:", accuracy_score(y_test, y_pred) * 100)

print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Test Accuracy: 75.14124293785311

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.81      0.81       114
           1       0.65      0.65      0.65        63

    accuracy                           0.75       177
   macro avg       0.73      0.73      0.73       177
weighted avg       0.75      0.75      0.75       177


Confusion Matrix:
 [[92 22]
 [22 41]]

In [16]:
print("CV Score:", grid_knn.best_score_ * 100)
print("Test Score:", accuracy_score(y_test, y_pred) * 100)

CV Score: 73.77581541091011
Test Score: 75.14124293785311

In [20]:
with open("model.pkl", "wb") as f:
    pickle.dump(best_rf, f)

print("Model saved!")

Model saved!